# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigoAsignatura', models.CharField(max_length=10)),
                ('creditos', models.IntegerField()),
                ('duracion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15)),
                ('codigoCarrera', models.IntegerField()),
                ('annoIngreso', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion', models.CharField(max_length=5)),
                ('anno', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('fin', models.CharField(max_length=5)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito.Asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoMalla', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaMalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMatriculados', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito.Estudiante')),
                ('mallacurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito.MallaCurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='mallacurricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito.MallaCurricular'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesorAsignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito.Profesor'),
        ),
    ]
