# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegadorcito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='password',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='password',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
    ]
